
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.example.invoiceservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2012-12-02T17:08:41.859+01:00
 * Generated source version: 2.7.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "InvoiceService",
                      portName = "InvoiceServiceSOAP",
                      targetNamespace = "http://www.example.org/InvoiceService/",
                      wsdlLocation = "http://www.example.org/?wsdl",
                      endpointInterface = "org.example.invoiceservice.InvoiceService")
                      
public class InvoiceServiceImpl implements InvoiceService {

    private static final Logger LOG = Logger.getLogger(InvoiceServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see org.example.invoiceservice.InvoiceService#addInvoice(org.example.messages.AddInvoiceRequestType  addInvoiceInput )*
     */
    public org.example.messages.AddInvoiceResponseType addInvoice(org.example.messages.AddInvoiceRequestType addInvoiceInput) throws AddInvoiceFault    { 
        LOG.info("Executing operation addInvoice");
        System.out.println(addInvoiceInput);
        try {
            org.example.messages.AddInvoiceResponseType _return = new org.example.messages.AddInvoiceResponseType();
            _return.setStatus("Status-887517272");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new AddInvoiceFault("addInvoiceFault...");
    }

}
