package si.fri.aws.dynamodb;

import java.util.Date;

import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBVersionAttribute;

@DynamoDBTable(tableName="WiMM_Invoices")
public class InvoiceEntityType {
	private String id;
	private String shopname;
	private String shopvat;
	private String itembarcode;
	private Float itemprice;
	private Integer itemquantity;
	private Date date;
	private String ownerId;
	private Integer version;
	
	@DynamoDBHashKey(attributeName="Id") 
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBAttribute(attributeName="shopname")
	public String getShopname() {
		return shopname;
	}
	public void setShopname(String shopname) {
		this.shopname = shopname;
	}
	
	@DynamoDBAttribute(attributeName="shopvat")	
	public String getShopvat() {
		return shopvat;
	}
	public void setShopvat(String shopvat) {
		this.shopvat = shopvat;
	}
	
	@DynamoDBAttribute(attributeName="itembarcode")
	public String getItembarcode() {
		return itembarcode;
	}
	public void setItembarcode(String itembarcode) {
		this.itembarcode = itembarcode;
	}
	
	@DynamoDBAttribute(attributeName="itemprice")
	public Float getItemprice() {
		return itemprice;
	}
	public void setItemprice(Float itemprice) {
		this.itemprice = itemprice;
	}
	
	@DynamoDBAttribute(attributeName="itemquantity")
	public Integer getItemquantity() {
		return itemquantity;
	}
	public void setItemquantity(Integer itemquantity) {
		this.itemquantity = itemquantity;
	}
	
	@DynamoDBAttribute(attributeName="date")
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	
	//rangeKey ?!? oO
	@DynamoDBAttribute(attributeName="ownerId")
	public String getOwnerId() {
		return ownerId;
	}
	public void setOwnerId(String ownerId) {
		this.ownerId = ownerId;
	}
	
	@DynamoDBVersionAttribute
	public Integer getVersion() { return version; }
	public void setVersion(Integer version) { this.version = version; }
}
